import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { ReduxProvider } from '@/app/Provider';
import Navbar from "@/components/Layout/Navbar.view";
import { categorySuggestions } from "@/utils/apiServices";
import { CatagorySugges, CatagorySuggestionsInfo } from "@/pageTypes/home.types";
import { getDictionary } from "./dictionaries";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ lang: 'en' | 'bl' }>
}>) {
   const categoryData: CatagorySugges = await categorySuggestions();
     const { lang } = await params
    const dict = await getDictionary(lang);
  return (
    <html lang={(await params).lang}>
      <body className={inter.className}>
        <ReduxProvider>
            <Navbar lang={dict}  categories={categoryData}/>
            {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
