// 'use client'
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { ReduxProvider } from '@/app/Provider';
import Navbar from "@/components/Layout/Navbar.view";
import { categorySuggestions } from "@/utils/apiServices";
import { CatagorySugges } from "@/pageTypes/home.types";
import { getDictionary } from "./dictionaries";
import Footer from "@/components/Home/Footer";
import { SessionProvider } from "next-auth/react";
import { auth } from "../lib/auth";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { siteConfig } from "@/config/config";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kabbik",
  description: "Generated by create next app",
  icons:{
    icon:siteConfig.logoWithoutKabbik
  }
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ lang: 'en' | 'bl' }>
}>) {
   const categoryData: CatagorySugges = await categorySuggestions();
     const { lang } = await params
    const dict = await getDictionary(lang);
    const session = await auth();
  return (
    <html lang={(await params).lang}>
      <body className={inter.className+" bg-bg"}>
        <ToastContainer/>
        <ReduxProvider>
            <Navbar lang={dict}  categories={categoryData}/>
            {/* <SessionProvider>{children}</SessionProvider> */}
            {children}
            <Footer/>
        </ReduxProvider>
      </body>
    </html>
  );
}
