import { loginWithPassword } from "./apiServices";

const BASE_URL = "https://api.kabbik.com";
// const BASE_URL = "http://localhost:8080/api";

export const apiEndPoints = {
  new_packageList:`${BASE_URL}/v3/googlepay/googlepay_subscription_list_v2`,
  packageList: `${BASE_URL}/v3/googlepay/googlepay_subscription_list`,
  topbannerImage: `${BASE_URL}/v4/home/getHomeBannerApp`,
  promoBannerList: `${BASE_URL}/v4/home/home-banner-list`,
  podcastList: `${BASE_URL}/v1/audiobooks/podcast-audiobooks`,
  favoriteAudioBookList: `${BASE_URL}/v1/favs/user-favs`,
  // audioBookDetails: `${BASE_URL}/v3/audiobooks/secured`,
  audioBookDetails: `${BASE_URL}/v3/audiobooks/single`,
  authorDetails: `${BASE_URL}/v1/audiobooks/authors/?name=`,
  authorEpisodes: `${BASE_URL}/v1/audiobooks/authors/authorepisodes?name=`,
  castCrewDetails: `${BASE_URL}/v1/audiobooks/castcrew/?name=`,
  castCrewEpisodes: `${BASE_URL}/v1/audiobooks/castcrew/castcrewaudiobook/?name=`,
  reviewList: `${BASE_URL}/v3/audiobooks/getallreview/?id=`,
  homeList: `${BASE_URL}/v4/home/home`,
  catagorySuggestions: `${BASE_URL}/v2/categories/suggestion`,
  catagoryItems: `${BASE_URL}/v2/audiobooks/category/`,
  homeCategoryItems: `${BASE_URL}/v1/audiobooks/home/seemore?name=`,
  catagoryList: `${BASE_URL}/v1/categories`,
  sendOtp: `${BASE_URL}/v1/auth/otpnew2`,
  sendOtpOlder: `${BASE_URL}/v1/auth/otpnew`,
  verifyOtp: `${BASE_URL}/v1/auth/otp/verify2`,
  loginWithPassword:`${BASE_URL}/v1/auth/login-password`,
  loginApi: `${BASE_URL}/v2/auth/login`,
  setPassword:`${BASE_URL}/v1/auth/set-password`,
  addReview: `${BASE_URL}/v2/audiobooks/`,
  favPostApi: `${BASE_URL}/v1/favs`,
  favDeleteApi: `${BASE_URL}/v1/favs/`,
  searchApi: `${BASE_URL}/v2/core/search`,
  upComingApi: `${BASE_URL}/v4/upcoming`,
  getuserProfileApi: `${BASE_URL}/v1/users/`,
  updateProfile: `${BASE_URL}/v1/users/update/withoutImage/`,
  bookRequestPostApi: `${BASE_URL}/v4/story/bookRequest`,
  bkashPaymentApi: `${BASE_URL}/v3/bkash/bkash-create-subscription-request-app`,
  bkashOneTimePaymentApi: `${BASE_URL}/v3/bkash/bkash-onetime-create-payment`,
  nagadPaymentApi: `${BASE_URL}/v4/nagad/create-payment`,
  upayPaymentApi: `${BASE_URL}/v4/upay/create-payment`,
  aamarpayPaymentAPi: `${BASE_URL}/v4/amrpay/create-payment-amrpay`,
  robiPaymentApi: `${BASE_URL}/v4/robi/create-payment`,
  blDcbPaymentApiUrl: `${BASE_URL}/v1/payment/create-bl-subscription`,
  blDcbVerifyApiUrl: `${BASE_URL}/v1/payment/verify-dcb-payment`,
  blDcbUnsubscribeApiUrl: `${BASE_URL}/v1/payment/unsubscribed-bl-dcb`,
  gpPaymentApi: `${BASE_URL}/v4/gp/create-payment`,
  verifyPayment: `${BASE_URL}/v1/payment/verify`,
  packDetailsApi: `${BASE_URL}/v3/googlepay/googlepay_subscription_item/?id=`,
  audioBookPlayCount: `${BASE_URL}/v2/audiobooks/`,
  episodePlayCount: `${BASE_URL}/v2/audiobooks/`,
  promoCodeGet: `${BASE_URL}/v4/home/checkPromoCode?`,
  userSummary: `${BASE_URL}/v1/kabbikanalytics/user-summary?userId=`,
  bkashUnSubscribeApi: `${BASE_URL}/v3/bkash/bkash-cancel-subscription-app`,
  robiUnsubscribeApi: `${BASE_URL}/v4/robi/robi-unsubscribe`,
  gpUnsubscribeApi: `${BASE_URL}/v4/gp/unsubscribe`,
  academicList: `${BASE_URL}/v4/academic`,
  redeemCodeApi: `${BASE_URL}/v4/user/redeem`,
  postGooglAuth: `${BASE_URL}/v2/auth/login-google`,
  premuimAudioBookList: `${BASE_URL}/v1/audiobooks/premium-audiobooks`,
  freeAudioBookList: `${BASE_URL}/v1/audiobooks/free-audiobooks`,
  accountDelete: `${BASE_URL}/v4/user/account-deletion-request`,
  // paymentMethodList: `${BASE_URL}/v4/user/paymentMethodListV3`,
  paymentMethodList: `${BASE_URL}/v4/user/paymentMethodListV4`,
  continueListeningPost: `${BASE_URL}/v4/user/continueWatchingWeb?user_id=`,
  continueListeningGet: `${BASE_URL}/v4/user/continueWatchingWeb?user_id=`,
  postCardNumber: `${BASE_URL}/v4/user/cardNumberSubmit`,
  userMembership: `${BASE_URL}/v4/user/membership`,
  bkashPurchaseAudiobook: `${BASE_URL}/v3/bkash/bkash-onetime-create-payment-audioBook-purchase`,
  getPurchasedAudiobooks: `${BASE_URL}/v1/audiobooks/get-all-purchased-audiobooks/`,
  getAllCourse: `${BASE_URL}/v4/course/get-all-course?userId=`,
  getPurchasedCourse: `${BASE_URL}/v4/course/get-all-purchase-course/`,
  bkashPurchaseCourse: `${BASE_URL}/v3/bkash/bkash-onetime-create-payment-course-purchase`,
  getStoreItem: `${BASE_URL}/v4/store/get-store-item`,
  getDynamicPaymentMethods: `${BASE_URL}/v4/home/get-dynamic-payment-method?purpose=`,
  currentEpisodePath: `${BASE_URL}/v1/episodes/signed-url`,
  sessionInit: `${BASE_URL}/v4/session/init-kabbik?`,
  sessionLog: `${BASE_URL}/v4/session/log-kabbik?`,
  postBlogUrl: `${BASE_URL}/v1/blog/create`,
  blogsUrl: `${BASE_URL}/v1/blog`,
  getApprovedBlogsUrl: `${BASE_URL}/v1/blog`,
  updateBlogUrl: `${BASE_URL}/v1/blog/update`,
  notificationGetUrl: `${BASE_URL}/v2/core/get-app-notifications`,
  markAsRead:`${BASE_URL}/v2/core/read-app-notification`,
  unreadCount:`${BASE_URL}/v2/core/get-user-unread-notifications`
};
