import { get } from "http";
import { loginWithPassword } from "./apiServices";

const BASE_URL = "https://api.kabbik.com";
// const BASE_URL = "http://localhost:8080/api";

export const apiEndPoints = {
  new_packageList:`${BASE_URL}/v3/googlepay/googlepay_subscription_list_v2`,
  packageList: `${BASE_URL}/v3/googlepay/googlepay_subscription_list`,
  topbannerImage: `${BASE_URL}/v4/home/getHomeBannerApp`,
  promoBannerList: `${BASE_URL}/v4/home/home-banner-list`,
  podcastList: `${BASE_URL}/v1/audiobooks/podcast-audiobooks`,
  favoriteAudioBookList: `${BASE_URL}/v1/favs/user-favs`,
  // audioBookDetails: `${BASE_URL}/v3/audiobooks/secured`,
  audioBookDetails: `${BASE_URL}/v3/audiobooks/single`,
  authorDetails: `${BASE_URL}/v1/audiobooks/authors/?name=`,
  authorEpisodes: `${BASE_URL}/v1/audiobooks/authors/authorepisodes?name=`,
  castCrewDetails: `${BASE_URL}/v1/audiobooks/castcrew/?name=`,
  castCrewEpisodes: `${BASE_URL}/v1/audiobooks/castcrew/castcrewaudiobook/?name=`,
  reviewList: `${BASE_URL}/v3/audiobooks/getallreview/?id=`,
  homeList: `${BASE_URL}/v4/home/home`,
  catagorySuggestions: `${BASE_URL}/v2/categories/suggestion`,
  catagoryItems: `${BASE_URL}/v2/audiobooks/category/`,
  homeCategoryItems: `${BASE_URL}/v1/audiobooks/home/seemore?name=`,
  catagoryList: `${BASE_URL}/v1/categories`,
  sendOtp: `${BASE_URL}/v1/auth/otpnew2`,
  sendOtpOlder: `${BASE_URL}/v1/auth/otpnew`,
  verifyOtp: `${BASE_URL}/v1/auth/otp/verify2`,
  loginWithPassword:`${BASE_URL}/v1/auth/login-password`,
  loginApi: `${BASE_URL}/v2/auth/login`,
  setPassword:`${BASE_URL}/v1/auth/set-password`,
  addReview: `${BASE_URL}/v2/audiobooks/`,
  favPostApi: `${BASE_URL}/v1/favs`,
  favDeleteApi: `${BASE_URL}/v1/favs/`,
  searchApi: `${BASE_URL}/v2/core/search`,
  upComingApi: `${BASE_URL}/v4/upcoming`,
  getuserProfileApi: `${BASE_URL}/v1/users/`,
  updateProfile: `${BASE_URL}/v1/users/update/withoutImage/`,
  bookRequestPostApi: `${BASE_URL}/v4/story/bookRequest`,
  bkashPaymentApi: `${BASE_URL}/v3/bkash/bkash-create-subscription-request-app`,
  bkashOneTimePaymentApi: `${BASE_URL}/v3/bkash/bkash-onetime-create-payment`,
  nagadPaymentApi: `${BASE_URL}/v4/nagad/create-payment`,
  upayPaymentApi: `${BASE_URL}/v4/upay/create-payment`,
  aamarpayPaymentAPi: `${BASE_URL}/v4/amrpay/create-payment-amrpay`,
  robiPaymentApi: `${BASE_URL}/v4/robi/create-payment`,
  blDcbPaymentApiUrl: `${BASE_URL}/v1/payment/create-bl-subscription`,
  blDcbVerifyApiUrl: `${BASE_URL}/v1/payment/verify-dcb-payment`,
  blDcbUnsubscribeApiUrl: `${BASE_URL}/v1/payment/unsubscribed-bl-dcb`,
  gpPaymentApi: `${BASE_URL}/v4/gp/create-payment`,
  verifyPayment: `${BASE_URL}/v1/payment/verify`,
  packDetailsApi: `${BASE_URL}/v3/googlepay/googlepay_subscription_item/?id=`,
  audioBookPlayCount: `${BASE_URL}/v2/audiobooks/`,
  episodePlayCount: `${BASE_URL}/v2/audiobooks/`,
  promoCodeGet: `${BASE_URL}/v4/home/checkPromoCode?`,
  userSummary: `${BASE_URL}/v1/kabbikanalytics/user-summary?userId=`,
  bkashUnSubscribeApi: `${BASE_URL}/v3/bkash/bkash-cancel-subscription-app`,
  robiUnsubscribeApi: `${BASE_URL}/v4/robi/robi-unsubscribe`,
  gpUnsubscribeApi: `${BASE_URL}/v4/gp/unsubscribe`,
  academicList: `${BASE_URL}/v4/academic`,
  redeemCodeApi: `${BASE_URL}/v4/user/redeem`,
  postGooglAuth: `${BASE_URL}/v2/auth/login-google`,
  premuimAudioBookList: `${BASE_URL}/v1/audiobooks/premium-audiobooks`,
  freeAudioBookList: `${BASE_URL}/v1/audiobooks/free-audiobooks`,
  accountDelete: `${BASE_URL}/v4/user/account-deletion-request`,
  // paymentMethodList: `${BASE_URL}/v4/user/paymentMethodListV3`,
  paymentMethodList: `${BASE_URL}/v4/user/paymentMethodListV4`,
  continueListeningPost: `${BASE_URL}/v4/user/continueWatchingWeb?user_id=`,
  continueListeningGet: `${BASE_URL}/v4/user/continueWatchingWeb?user_id=`,
  postCardNumber: `${BASE_URL}/v4/user/cardNumberSubmit`,
  userMembership: `${BASE_URL}/v4/user/membership`,
  bkashPurchaseAudiobook: `${BASE_URL}/v3/bkash/bkash-onetime-create-payment-audioBook-purchase`,
  getPurchasedAudiobooks: `${BASE_URL}/v1/audiobooks/get-all-purchased-audiobooks/`,
  getAllCourse: `${BASE_URL}/v4/course/get-all-course?userId=`,
  getPurchasedCourse: `${BASE_URL}/v4/course/get-all-purchase-course/`,
  bkashPurchaseCourse: `${BASE_URL}/v3/bkash/bkash-onetime-create-payment-course-purchase`,
  getStoreItem: `${BASE_URL}/v4/store/get-store-item`,
  getDynamicPaymentMethods: `${BASE_URL}/v4/home/get-dynamic-payment-method?purpose=`,
  currentEpisodePath: `${BASE_URL}/v1/episodes/signed-url`,
  sessionInit: `${BASE_URL}/v4/session/init-kabbik?`,
  sessionLog: `${BASE_URL}/v4/session/log-kabbik?`,
  postBlogUrl: `${BASE_URL}/v1/blog/create`,
  blogsUrl: `${BASE_URL}/v1/blog`,
  getApprovedBlogsUrl: `${BASE_URL}/v1/blog`,
  updateBlogUrl: `${BASE_URL}/v1/blog/update`,
  notificationGetUrl: `${BASE_URL}/v2/core/get-app-notifications`,
  markAsRead:`${BASE_URL}/v2/core/read-app-notification`,
  unreadCount:`${BASE_URL}/v2/core/get-user-unread-notifications`,
  create_email_notification:`${BASE_URL}/v4/email-notification/create-notification`,
  create_preference:`${BASE_URL}/v4/user-preference/create`,
  get_preference:`${BASE_URL}/v4/user-preference/get-single`,
  get_authors:`${BASE_URL}/v4/authors/get-authors`,
  get_playlist_books:`${BASE_URL}/v1/playlist/get-folder-books-user`,
  update_playlist_folder:`${BASE_URL}/v1/playlist/update-folders`,
  create_new_folders:`${BASE_URL}/v1/playlist/create-folder`,
  add_books_tofolder:`${BASE_URL}/v1/playlist/add-book-playlist`,
  removeBooksFromPlaylist:`${BASE_URL}/v1/playlist/`,
  sponsor_request:`${BASE_URL}/v4/home/sponsor-request`,
  // reward point
  create_reward: `${BASE_URL}/v4/reward/create-reward`,
  // ?userId=1323204&taskId=1
  claim_reward:`${BASE_URL}/v4/reward/claim-reward`,
  all_tier_reward:`${BASE_URL}/v4/reward/get-all-tier_reward`,
  // ?userId=33677
  getUser_reward_profile:`${BASE_URL}/v4/reward/get-user-reward-profile`,
  // ?userId=1323204
  reward_faq:`${BASE_URL}/v4/reward/tier-faq`,
  reward_tasks:`${BASE_URL}/v4/reward/get-all-task`,
  user_point_details:`${BASE_URL}/v4/reward/user-point-details`,
  // ?type=earned&userId=1323204&page=1&limit=15
  // refer and earn
  insert_earn_log:`${BASE_URL}/v4/refer/earn-log`,
  claim_request:`${BASE_URL}/v4/refer/claim-request`,
  user_earning:`${BASE_URL}/v4/refer/get-user-earning`,
  // ?userId=33677
  user_claim_history:`${BASE_URL}/v4/refer/get-claim-history`,
  // ?userId=1323204&fromDate=2025-08-03&toDate=2025-09-09&status=ALL
  get_refer_history:`${BASE_URL}/v4/refer/get-refer-history`
  // ?userId=1323204&fromDate=2025-09-04&toDate=2025-09-11
};
